= Object.defineProperties
:source-highlighter: highlight.js
:pygments-style: xcode
:highlightjs-theme: xcode

[source,javascript]
====
include::res/example1.js[]
====


== Syntax
====
Object.defineProperty(obj, prop, descriptor)
====
* obj
+
The object on which to define the property.
* prop
+
The name or Symbol of the property to be defined or modified.
* descriptor
+
The descriptor for the property being defined or modified.

== Description
* By default, properties added using Object.defineProperty() are not writable, not enumerable, and not configurable.
* Property descriptors present in objects come in two main flavors: data descriptors and accessor descriptors.

=== data descriptor has
* value(default:undefined)
+
====
The value associated with the property. Can be any valid JavaScript value (number, object, function, etc.).
====

* writable
+
====
true if the value associated with the property may be changed with an assignment operator. 
====

=== accessor descriptor has
* get(default:undefined)
+
====
A function which serves as a getter for the property, or undefined if there is no getter. When the property is accessed, this function is called without arguments and with this set to the object through which the property is accessed (this may not be the object on which the property is defined due to inheritance). The return value will be used as the value of the property. 
====
* set(default:undefined)
+
====
A function which serves as a setter for the property, or undefined if there is no setter. When the property is assigned, this function is called with one argument (the value being assigned to the property) and with this set to the object through which the property is assigned.
====

=== both have
* configurable(default:false)
+
====
when this is set to false,

* the type of this property cannot be changed between data property and accessor property
* the property may not be deleted
* other attributes of its descriptor cannot be changed (however, if it's a data descriptor with writable: true, the value can be changed, and writable can be changed to false).
====

* enumerable(default:false)
+
====
true if and only if this property shows up during enumeration of the properties on the corresponding object.
====

[NOTE]
====
Bear in mind that these attributes are not necessarily the descriptor's own properties. Inherited properties will be considered as well. In order to ensure these defaults are preserved, you might freeze existing objects in the descriptor object's prototype chain upfront, specify all options explicitly, or point to null with Object.create(null).
====